name: iphone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.4+4
  shared_preferences: ^2.5.1
  syncfusion_flutter_charts: ^28.2.5+1
  table_calendar: ^3.0.3
  fl_chart: ^0.70.2
  flutter_screenutil: <=5.9.1
  device_preview_plus: ^2.2.4
  intl: ^0.19.0
  flutter_datetime_picker: ^1.5.1
  url_launcher: 6.3.1
  flutter_localizations:
    sdk: flutter
  uuid: ^4.5.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  generate: true
  assets:
    - assets/onboarding 41.svg
    - assets/statbar.svg
    - assets/onboarding 42.svg
    - assets/onboarding 43.svg
    - assets/onboarding 41.png
    - assets/onboarding 42.png
    - assets/onboarding 43.png
    - assets/launch1.svg
    - assets/launch.png
    - assets/settings.png
    - assets/knowledge.png
    - assets/fingram.png
    - assets/sovet.png
    - assets/zashita.png
    - assets/zashitadannih.png
    - assets/pustaya.png
    - assets/Expenses.png
    - assets/redaktor.png
    - assets/3.svg
    - assets/statusbarmain.svg
    - assets/saved.png
    - assets/saved2.png
    - assets/1.svg
    - assets/2.svg
    - assets/4.svg
    - assets/5.svg
    - assets/33.svg
    

  uses-material-design: true
